criaCartao('Vocabulário', 'Como se diz "olá" em inglês?', 'Hello')
criaCartao('Vocabulário', 'Como se diz "tchau" em inglês?', 'Goodbye')
criaCartao('Gramática', 'Qual a forma correta do verbo "to be" no presente para "he" ou "she"?', 'is')
criaCartao('Vocabulário', 'O que significa "book" em português?', 'livro')
criaCartao('Gramática', 'Como se forma o plural de "cat"?', 'cats')
criaCartao('Vocabulário', 'Como se diz "gato" em inglês?', 'cat')
criaCartao('Gramática', 'Qual é o verbo auxiliar para formar perguntas no presente em inglês?', 'do')
criaCartao('Vocabulário', 'O que significa "dog" em português?', 'cachorro')
criaCartao('Vocabulário', 'Como se diz "feliz" em inglês?', 'happy')
criaCartao('Gramática', 'Qual a forma do verbo "to be" para "I"?', 'am')
criaCartao('Vocabulário', 'O que significa "car" em português?', 'carro')
criaCartao('Gramática', 'Qual é a forma do verbo "to be" para "they"?', 'are')
criaCartao('Vocabulário', 'Como se diz "casa" em inglês?', 'house')
criaCartao('Gramática', 'Como se forma o futuro simples com "will"?', 'Sujeito + will + verbo principal')
criaCartao('Vocabulário', 'Como se diz "escola" em inglês?', 'school')
criaCartao('Vocabulário', 'O que significa "tree" em português?', 'árvore')
criaCartao('Gramática', 'Como é a estrutura básica de uma frase afirmativa no presente?', 'Sujeito + verbo + complemento')
criaCartao('Vocabulário', 'Como se diz "livro" em inglês?', 'book')
criaCartao('Gramática', 'Qual a forma do verbo "to have" para "he"?', 'has')
criaCartao('Vocabulário', 'O que significa "chair" em português?', 'cadeira')
criaCartao('Vocabulário', 'Como se diz "janela" em inglês?', 'window')
criaCartao('Vocabulário', 'Como se diz "feliz" em inglês?', 'happy')
criaCartao('Gramática', 'Como é a estrutura de uma pergunta no presente simples?', 'Do/Does + sujeito + verbo?')
criaCartao('Vocabulário', 'Como se diz "amigo" em inglês?', 'friend')
criaCartao('Vocabulário', 'O que significa "computer" em português?', 'computador')
criaCartao('Vocabulário', 'Como se diz "trabalho" em inglês?', 'work')
criaCartao('Gramática', 'Qual a forma do verbo "to be" para "we"?', 'are')
criaCartao('Vocabulário', 'Como se diz "praia" em inglês?', 'beach')
criaCartao('Vocabulário', 'O que significa "city" em português?', 'cidade')
criaCartao('Gramática', 'Qual é a forma do verbo "to be" para "I"?', 'am')
criaCartao('Vocabulário', 'Como se diz "comida" em inglês?', 'food')
criaCartao('Gramática', 'Como se faz a negativa no presente simples?', 'Sujeito + do/does + not + verbo')
criaCartao('Vocabulário', 'Como se diz "refrigerante" em inglês?', 'soda')
criaCartao('Vocabulário', 'O que significa "street" em português?', 'rua')
criaCartao('Vocabulário', 'Como se diz "estrela" em inglês?', 'star')
criaCartao('Gramática', 'Como se diz "Eu gosto de" em inglês?', 'I like')
criaCartao('Vocabulário', 'O que significa "bird" em português?', 'pássaro')
criaCartao('Gramática', 'Como se diz "não" em inglês?', 'no')
criaCartao('Vocabulário', 'Como se diz "noite" em inglês?', 'night')
criaCartao('Gramática', 'Qual é a forma negativa do verbo "to be" no presente?', 'am not, is not, are not')
criaCartao('Vocabulário', 'Como se diz "agua" em inglês?', 'water')
criaCartao('Gramática', 'Como se faz uma pergunta com o verbo "to be"?', 'Inverter a ordem do sujeito e do verbo ("Are you...?", "Is he...?")')
criaCartao('Vocabulário', 'O que significa "bus" em português?', 'ônibus')
criaCartao('Gramática', 'Como se diz "nós temos" em inglês?', 'we have')
criaCartao('Vocabulário', 'Como se diz "mãe" em inglês?', 'mother')
criaCartao('Vocabulário', 'O que significa "rain" em português?', 'chuva')
criaCartao('Vocabulário', 'Como se diz "cachorro" em inglês?', 'dog')
criaCartao('Gramática', 'Como se diz "você está" em inglês?', 'you are')
criaCartao('Vocabulário', 'O que significa "sun" em português?', 'sol')
criaCartao('Gramática', 'Como se diz "eles/elas estão" em inglês?', 'they are')
criaCartao('Vocabulário', 'Como se diz "carro" em inglês?', 'car')
criaCartao('Vocabulário', 'O que significa "apple" em português?', 'maçã')
criaCartao('Gramática', 'Qual a forma do verbo "to be" para "it"?', 'is')
criaCartao('Vocabulário', 'Como se diz "aeroporto" em inglês?', 'airport')
